version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tomatored
    ports:
      - "5432:5432"
    volumes:
      - C:/services/docker/volumes/postgres:/var/lib/postgresql/data
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=dluffy
      - KEYCLOAK_ADMIN=dluffy
      - KEYCLOAK_ADMIN_PASSWORD=nico
      - KEYCLOAK_PASSWORD=nico
      - DB_ADDR=192.168.0.160 # this is my local api address
      - DB_DATABASE=identity
      - DB_USER=identity
      - DB_PASSWORD=redtomatoes
    depends_on:
      - postgres

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    volumes:
      - C:/services/docker/volumes/zookeeper:/var/lib/zookeeper/log
#    ports:
#      - '2181:2181'
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - '9092:9092'
      - '29092:29092'
    volumes:
      - C:/services/docker/volumes/kafka:/var/lib/kafka/data

  connect:
    image: debezium/connect
    container_name: debezium
    depends_on:
      - kafka
      - zookeeper
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=cdc_connect_configs
      - OFFSET_STORAGE_TOPIC=cdc_connect_offsets
      - STATUS_STORAGE_TOPIC=cdc_connect_statuses
    ports:
      - '8083:8083'







